# Use postgres/example user/password credentials
version: "3.9"

services:
  db:
    container_name: cesizen
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: cesizen
    ports:
      - "5432:5432"
